### ISSUE TITLE
Textures are not fully loaded

### ISSUE THREAD

**Issue by CrazyFlasher** [Gamua/Starling-Framework#972] opened 2017-06-07 08:54 UTC
Hi.
On some android devices, textures are not fully displayed:
http://joxi.net/nAyQ6kpIZKPLAZ
http://joxi.net/Dr819ZafNROam6
http://joxi.net/E2pLnK3cKzPn2Y
Are there any ways to fix it?
Starling 2.1 release, AIR 25

**Comment by PrimaryFeather** [comment] 2017-06-07 15:04
You are sure you are using the 2.1 _release_, not the current head revision, right? (In this specific case, it could make a [difference](https://forum.starling-framework.org/topic/starling-crashing-immediately-after-launch-on-android-with-github-src#post-104979). Also, have you tried the latest AIR 26 beta?

**Comment by CrazyFlasher** [comment] 2017-06-07 17:05
yes, this bug was reported by users for the project, that was built using Starling 2.1 latest release (not latest repo version) with AIR 25.

**Comment by CrazyFlasher** [comment] 2017-06-08 11:54
Unfortunately, I didn't get this issue on my devices. And I'm afraid to build app using AIR 26 beta

**Comment by PrimaryFeather** [comment] 2017-06-08 13:42
Ah, I see. Hm, yeah, I can understand that you don't want to take the risk of using the beta version for the release. Do you know how many users are affected by this? I.e. how serious this issue is?

I'm afraid there's not really much I can do to help, though. 😣 
The only chance we have to get this fixed is provide Adobe with a sample they can reproduce.

**Comment by CrazyFlasher** [comment] 2017-06-08 13:53
They say: "Who doesn't risk - doesn't drink champagne" :)
I'll release with AIR 26 beta and lets see if users will report it again.

**Comment by PrimaryFeather** [comment] 2017-06-08 13:55
Haha, that's the spirit! :grinning:

Just in case you're updating Starling too, don't forget to deactivate that `Texture.asyncBitmapUploadSupported` property, though. Leaving it enabled would be asking for trouble. :wink:

**Comment by PrimaryFeather** [comment] 2017-06-24 17:24
I'll close this issue, since it's an AIR problem that has been reported, and I can't do much else to help. Feel free to open it again if required.

**Closed by PrimaryFeather** 2017-06-24 17:24 UTC
