### ISSUE TITLE
help！Texture has something wrong

### ISSUE THREAD

**Issue by godou** [Gamua/Starling-Framework#755] opened 2015-08-17 08:17 UTC
ATF version 3 ETC1 \ air 18 \ android 5.1 \ starling 1.7.1

The Texture is mismatch times.
http://a.disquscdn.com/uploads/mediaembed/images/2396/8167/original.jpg?w=600&h

help！

**Comment by PrimaryFeather** [comment] 2015-08-17 08:36
Are you using the ATF tools that are coming with AIR 18? 
Please also try the tools from the latest AIR 19 beta — Adobe recently fixed some things in that respect.

If none of this helps, please create a complete description of the problem:

* Include the original image you're converting to ATF.
* Describe the exact arguments to used to create the ATF file.
* And the resulting ATF file, as well as a screenshot showing how that image looks on your device.
* Also include the exact vendor, model and version of the device that shows the problem.

Then report this to [bugbase.adobe.com](https://bugbase.adobe.com), and post the link here, so that people now about it and can vote for it.

Thx!

**Comment by godou** [comment] 2015-08-17 09:27
using  air 18 \ atf version 2 \ android 5.1 \ starling 1.5.1  is OK

**Comment by PrimaryFeather** [comment] 2015-08-18 07:43
Even in that case, I'd need the information described above. :wink:

**Comment by godou** [comment] 2015-08-18 07:58
oh sorry. This is info.
Phone: sony C6603 LT36H 
version2 arguments ：png2atf.exe -i texture.png -o texture.atf -c e -n 0,0 -q 30
version3 arguments ：png2atf.exe -i texture.png -o texture.atf -c e -n 0,0 -q 0
image：http://www.filedropper.com/textures_3   original image & version2 atf & version3 atf

Thank you very much.

**Comment by hejiacong** [comment] 2015-08-19 02:47
What change in AIR 19 about atftools,why we can't see anything in the release notes?

**Comment by PrimaryFeather** [comment] 2015-08-19 09:37
@hejiacong That was done in AIR 18: they added support for ETC2 compression. Here are the release notes: https://helpx.adobe.com/flash-player/release-note/fp_18_air_18_release_notes.html

**Comment by PrimaryFeather** [comment] 2015-08-24 09:44
@godou I cannot open the filedropper link you posted. Could you check that?

Furthermore, what's "version2" and "version3"? I'm not sure I understand the problem description correctly, please try to be more clear in your error documentation.

To summarize, please send the following

1) ONE png file that you converted
2) ONE atf file that you created from that PNG
3) The png2atf command that you used to create the ATF file
4) A screenshot from the output on a device where it's working
5) A screenshot from the output on a device where it's not working.

Thanks!

**Comment by godou** [comment] 2015-09-10 08:42
sorry!
http://123.59.11.151/other/texture_s.rar

**Comment by tk-kawakami** [comment] 2015-11-12 14:33
I was also faced with the same problem as this matter on android.
Image of the problem attached here.
![screenshot_1](https://cloud.githubusercontent.com/assets/15812917/11120788/74cc1c1a-8995-11e5-8611-c98cf521f4c1.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/15812917/11120801/83a4c5ca-8995-11e5-99d7-8ed2e228b31e.png)
Attached image is made by ‘png2atf.exe -c e -r’.

Etc1 format is best for my project. It is because it reduce the resource requirements.
But some recent device is not worked. It has been occurred problem of the attached image.
Model are as follows. (It is typical of each GPU)
- Sony Xperia Z4 (Snapdragon810 (MSM8994) / Adreno430)
- Huawei P8max (Kirin930 / Mali-T628 MP4)
- Sumsung Galaxy S6 (Exynos7 Octa (Exynos7420) / Mali-T760 MP8)

I have tried the following settings, but none did not go well.
- png2atf.exe use ‘-c e’ with various options, -‘r’, not use ‘-r’, ‘-n 0,0’.
- starling 1.5.1 / 1.7
- starling used Stage3D-profile is “auto”, “standardExtended”
- Try ETC2 (png2atf.exe -c e2)  * Nothing was not drawn in ETC2 on all android devices I tried.

Right now, I’m considering the replacement of png, resource limitations tight due to the large consumption of VRAM resources .
By all means, I want to improve and to work with ETC1.

**Comment by PrimaryFeather** [comment] 2015-11-13 08:04
Thanks for the detailed report! I added a link to both of your descriptions to [Adobe's issue tracker](https://bugbase.adobe.com/index.cfm?event=bug&id=%20%20%20%203961778) — please vote for it, or add comments with additional information. That's our best chance to get it fixed soon!

**Comment by tk-kawakami** [comment] 2015-11-13 11:44
Thank you for your introducing!
I voted for Adobe's issue tracker.
I hope it will be fixed quickly,too.

**Comment by sdcinglis** [comment] 2015-11-13 20:38
I've also found this issue with the new Nexus 5x and 6p devices which should hopefully raise some red flags over at Adobe

**Comment by PrimaryFeather** [comment] 2015-11-15 13:55
@sdcinglis: definitely add that information to the bugbase issue, if it's not already part of it. Agreed, such devices must be fully compatible!!

**Comment by PrimaryFeather** [comment] 2015-12-10 08:10
Good news, everyone! In [this bugbase issue](https://bugbase.adobe.com/index.cfm?event=bug&id=3961778), Adobe reported that they fixed the problem with AIR 20.0.215.

Could you guys try that out and find out if the fix works for you? Thanks a lot in advance!

**Comment by TheStalwart** [comment] 2016-02-18 13:56
The issue is still reproducible after rebuilding ATFs with 21.0.0.150, setting app namespace to 21.0 and swf-version to 32.
Device is LG Nexus 5X.

**Comment by gtribut** [comment] 2016-03-01 14:27
I finally get it working for me, after lots of tests and recompilation of my ATF textures, I have found that I just need to recompile my app with AIR SDK 21.0.0.150 (last beta), and it works even with my previous ATF textures made from atftools in Adobe Gaming SDK 1.4

**Comment by TheStalwart** [comment] 2016-03-10 15:56
Issue is still reproducible with AIR SDK 21.0.0.176 released today. @gtribut what's your test hardware? I'm testing on LG Nexus 5X

**Comment by TheStalwart** [comment] 2016-04-11 10:20
Issue is still reproducible with AIR SDK 22.0.0.89

**Comment by gtribut** [comment] 2016-04-18 15:25
@TheStalwart I get the problem on some Android devices (Huawei MT7-L09 - Processeur Hisilicon Kirin 925 - Android 4.4.2), on my nexus 5, no problems...

**Comment by TheStalwart** [comment] 2016-04-18 15:28
@gtribut i'm able to reproduce on following devices:
- LG Nexus 5X 
- Huawei G7 Plus 
- OPPO R7s 
- HTC One E9PLUS

**Comment by TheStalwart** [comment] 2016-05-26 12:05
Issue is still reproducible with AIR SDK 22.0.0.149 released today

**Comment by TheStalwart** [comment] 2016-06-20 12:19
Issue is still reproducible with AIR SDK 22.0.0.153 released last friday

**Comment by TheStalwart** [comment] 2016-08-02 16:34
Issue seems to be fixed in AIR SDK 23.0.0.215.

Tested on following devices:
LG Nexus 5X
Huawei G7 Plus
OPPO R7s
Samsung Galaxy S6
Samsung Galaxy Edge+
HTC One E9PLUS

**Comment by PrimaryFeather** [comment] 2016-08-04 09:06
Finally, it seems Adobe has fixed this issue!
Thanks a lot for everyone involved - including the users who kept reporting the issues, and the team at Adobe for fixing the problems. 👍 

For reference, here's the issue on Adobe's bugbase: https://bugbase.adobe.com/index.cfm?event=bug&id=3961778

I'll close this one here, then.

**Closed by PrimaryFeather** 2016-08-04 09:06 UTC
Labels: Bug in Flash/AIR

**Comment by pSi-X** [comment] 2016-08-04 10:29
F@ck yeah!!!

**Comment by matrix3d** [comment] 2017-01-20 07:51
pls open it,the xiaomi air24 with -c e -r.
with alpha,have bug
