### ISSUE TITLE
FireFox 55 baselineConstrained Bug

### ISSUE THREAD

**Issue by rtalon83** [Gamua/Starling-Framework#999] opened 2017-08-30 06:28 UTC
Hi everybody!

There is a huge bug in Starling with the new Firefox 55 version. The last parameter in constructor "baselineConstrained" causes an error in firefox, your memory is increasing all the time until broken the browser. 
This bug is fixed changing the last parameter with "auto".

You're welcome!

**Comment by PrimaryFeather** [comment] 2017-08-30 09:28
Thanks a lot for the report!

Could you please tell me which operating system you were running Firefox on? I just tested this with Firefox 55 on macOS and can't reproduce the problem.

Do you experience the problem with this demo? (Runs in constrained mode.)
https://gamua.com/media/starling/demos/flappy-starling/index-constrained.html

**Comment by rtalon83** [comment] 2017-08-30 09:55
Hi!!
Yes, in Windows 7 with Firefox 55 your demo causes the problem. I don't know what happend in MacOs or Linux, only I tested in Windows 7, 8 and 10.

[http://imgur.com/a/eGvPb](url)

**Comment by PrimaryFeather** [comment] 2017-08-30 11:52
I created a report for Adobe. Please vote for the issue [here](https://github.com/Gamua/Adobe-Runtime-Support/issues/18) and [here](https://tracker.adobe.com/#/view/FP-4198562)!

Since there's nothing I can do about it in Starling, I'll close this issue now.

**Closed by PrimaryFeather** 2017-08-30 11:52 UTC

**Comment by PrimaryFeather** [comment] 2017-08-30 12:21
One last thing: what's the Flash Player version you tested this with?

**Comment by rtalon83** [comment] 2017-08-30 12:38
26.0.0.126
26.0.0.151
Normal and Debugger
4-5 months ago I saw the error with Firefox Developers edition 55b ( more or less ) and the flash player was 25 or 24 ( I don't remember )

**Comment by PrimaryFeather** [comment] 2017-08-30 12:39
Thx!!
