### ISSUE TITLE
Losing Stage3D Context results in runtime exception

### ISSUE THREAD

**Issue by vpmedia** [Gamua/Starling-Framework#688] opened 2015-03-06 17:33 UTC
The exception does not occur every time when losing stage3d context, just when some conditions are met (which I was not able to figure out yet..). But both Debug and Release SWF failed with this:

    TypeError: Error #1006: value is not a function.
	at starling.textures::ConcreteTexture/onContextCreated()[\starling\textures\ConcreteTexture.as:220]
	at starling.events::EventDispatcher/invokeEvent()[\starling\events\EventDispatcher.as:145]
	at starling.events::EventDispatcher/dispatchEvent()[\starling\events\EventDispatcher.as:117]
	at starling.events::EventDispatcher/dispatchEventWith()[\starling\events\EventDispatcher.as:195]
	at starling.core::Starling/initializeGraphicsAPI()[\starling\core\Starling.as:446]
	at starling.core::Starling/initialize()[\starling\core\Starling.as:429]
	at starling.core::Starling/onContextCreated()[\starling\core\Starling.as:678]

I think mRestore() is called without null check.

**Comment by PrimaryFeather** [comment] 2015-03-07 14:32
Wow, now this is odd. Yes, the "mOnRestore" function is called without a null check, and I could easily add one. BUT: if you look at the code, "mOnRestore" is only called in "onContextCreated", and that callback is only every added if "mOnRestore" has a value. So, WTF?! Am I overlooking something here?

**Comment by vpmedia** [comment] 2015-03-07 15:02
Yes I see... It is really weird. 
I can easily reproduce the issue on Windows 7 (IE+FF) using CTRL-ALT-DEL which triggers a Stage3D Context loss.. But my app. uses too many textures with a relatively huge codebase so I'll try to make a simple HelloWorld example to reproduce the exception, so it will be easier to find the cause..

**Comment by vpmedia** [comment] 2015-03-07 15:04
Also I'll try to add this mOnRestore != null check, see what happens after...

**Comment by PrimaryFeather** [comment] 2015-03-07 15:05
That would be a huge help, thanks!
So you say this happens almost every time when you try it in Windows?

**Comment by vpmedia** [comment] 2015-03-07 15:07
Yes but only using a browser.. with the standalone player the stage3d context recovers and I see my game working..

**Comment by vpmedia** [comment] 2015-03-07 15:18
Added check:

    if(mOnRestore != null) {
            mOnRestore();
    } else {
           trace(this, "mOnRestore is null, what the heck...", mDataUploaded, format, width, height);
    }

Recieved output:

    [trace] [object ConcreteTexture] mOnRestore is null, what the heck... false bgra 866 591
    [trace] [object ConcreteTexture] mOnRestore is null, what the heck... false bgra 866 591

I've to check my textures because as far as I remember I don't use 866 wide ones at all.. : )

But also I don't see any visual errors after implementing the null check so my game screen recovers. I've to test this more..

**Comment by vpmedia** [comment] 2015-03-07 18:49
I had some success to scope down the problem to the PixelMask extension..

**Comment by vpmedia** [comment] 2015-03-07 18:53
Also I see you have contributed to this class, any tips what can be wrong with Stage3dContextLoss handling?
https://github.com/jonathanhart/pixelmask/commit/82c5815fa85ca16ae1a6039336b7bb9a76d8c776

**Comment by vpmedia** [comment] 2015-03-07 21:47
I've tried to mimic the PixelMasker class logic, here we go:

    private var rt:RenderTexture;
    
    public function TesterContext() {
        addEventListener(Event.ADDED, onAdded);
    }

    private function onAdded(event:Event):void {
        removeEventListener(Event.ADDED, onAdded);
        Starling.current.addEventListener(Event.CONTEXT3D_CREATE, onContextCreated);
        rt =  new RenderTexture(300, 200, false, 1);
    }

    private function onContextCreated(event:Event):void {
        rt.dispose();
        rt =  new RenderTexture(300, 200, false, 1);
    }
    
Trace output:

    [trace] [Starling] Initialization complete.
    [trace] [Starling] Display Driver: DirectX9 (Standard)
    XXX !!! Loose Stage3D Context Here !!! XXX
    [trace] [Starling] Initialization complete.
    [trace] [Starling] Display Driver: DirectX9 (Standard)
    [trace] [object ConcreteTexture] mOnRestore is null, what the heck... false bgra 300 200

So even a dummy RenderTexture disposed after CONTEXT3D_CREATE results a null mOnRestore..

**Comment by vpmedia** [comment] 2015-03-07 22:11
I'm not sure why but this one works:

    rt =  new RenderTexture(300, 200, false, 1);
    rt.root.onRestore = function(){trace("Custom Restore..")};
    Starling.current.addEventListener(Event.CONTEXT3D_CREATE, onContextCreated);
    =Loose context here=
    'Custom Restore' traced.. and 'mOnRestore' is NOT null

But this one don't:

    Starling.current.addEventListener(Event.CONTEXT3D_CREATE, onContextCreated);
    rt =  new RenderTexture(300, 200, false, 1);
    rt.root.onRestore = function(){trace("Custom Restore..")};
    =Loose context here=
    'Custom Restore' NOT traced.. and 'mOnRestore' is NULL

So depending on the order of RenderTexture instantiation and the CONTEXT3D_CREATED event attachment, I'm getting different results. Funny stuff..

**Comment by jamikado** [comment] 2015-03-07 22:16
OK so if there is a RenderTexture involved, I think I see where the problem could be occurring. A RenderTexture uses an internal mActiveTexture ConcreteTexture which sets up its own onRestore which them makes it also a listener for Event.CONTEXT3D_CREATE.  If you are going to call rt.dispose() on the RenderTexture, this will also call dispose on its internal mActiveTexture which will nil its own onRestore, but since you are calling this dispose inside a Event.CONTEXT3D_CREATE listener, it is probably the mActiveTexture instance that is also in the current list of listeners and is later in the list so it is going to get its Event.CONTEXT3D_CREATE listener called (but you nulled its onRestore).

Normally I guess people aren't calling dispose on normal textures in this Event.CONTEXT3D_CREATE callback, but in the case of RenderTexture, if you need to dispose() it in this callback because other items in RenderTexture need cleaned up, then something needs to address the mActiveTexture also getting its dispose() call as a sideeffect but also being in the active set of listeners...

**Comment by vpmedia** [comment] 2015-03-07 22:21
Plus note:

This one triggers the exception: Error #1006: value is not a function. - if the RenderText is disposed..

    Starling.current.addEventListener(Event.CONTEXT3D_CREATE, onContextCreated);

This one seem to work OK every time:

    Starling.current.stage3D.addEventListener(Event.CONTEXT3D_CREATE, onContextCreated, false, 0, true);

As I've search through the source codes it varies which one is used (in extensions mostly..).

Also thanks for shedding light on the onRestore logic..

**Comment by PrimaryFeather** [comment] 2015-03-09 13:05
Thanks a lot for the experiments to reproduce the problem! Jeff, you're on spot, that's definitely the problem. That situation just didn't come to my mind ...

In any case, checking that function for being null is definitely the way to go, then. That doesn't have any negative side effects, and it fixes that specific case.

Thanks for the help, guys! Merged with #689

**Closed by PrimaryFeather** 2015-03-09 13:05 UTC
Labels: Bug
