### ISSUE TITLE
Adobe AIR17. Starling does't run on some devices. May be Agal v3?

### ISSUE THREAD

**Issue by Mintonist** [Gamua/Starling-Framework#695] opened 2015-03-25 13:36 UTC
We have a game on Android Market, that uses Starling.
After AIR17 integration (without code changes) we have many complaints (~5% of users) from our players that game is not loading and stops at startscreen. Seems it hapens when Starling is initialized.
We return AIR16 and it fixes this problem.

With AIR16 we add new profiles ("standard", "standardConstrained") in Straling class.

private function requestContext3D(stage3D:Stage3D, renderMode:String, profile:Object):void
 {
            var profiles:Array;
            var currentProfile:String;
            
            if (profile == "auto")
                profiles = ["standard", "standardConstrained", "baselineExtended", "baseline", "baselineConstrained"];
....
}

I think that problem is in AGALMiniAssembler. We use standart Starling ColorMatrixFilter and BlurFilter, that uses AGALMiniAssembler.
But according to AIR17 changelog (https://helpx.adobe.com/flash-player/release-note/fp_17_air_17_release_notes.html) new AGALMiniAssembler need only for new "standardExtended" profile. 

Can we use AGALMiniAssembler version 3 (https://github.com/adobe-flash/graphicscorelib/blob/master/src/com/adobe/utils/v3/AGALMiniAssembler.as)? It has other package name com.adobe.utils.v3.

Or may be our problem is same as this issue https://github.com/Gamua/Starling-Framework/issues/676

List of devices (form google dev console):
Galaxy Tab4 7.0 (degas3g)
Galaxy Tab2 10.1 (espresso10rf)
Galaxy S Advance (GT-I9070)
Galaxy Tab3 Lite (goya3g)
ASUS Fonepad ME371MG (ME371MG)
Galaxy Tab3 7.0 (lt023g)
MediaPad 7 Lite (hws7930u)

**Comment by PrimaryFeather** [comment] 2015-03-25 16:32
Thanks for the report! I'm sure your problem is the one from issue #676, though.
The AGALMiniAssembler hasn't change much, actually — only a few of the limits (how many of certain registers are available, etc.) have been raised. 

You see the changes here:

https://github.com/Gamua/Starling-Framework/commit/03d6cbbde0eea1048a7e87c651c8f10192caab78#diff-06321da11ac0664dc04efa5ce488c629

I'll close this issue, since it's thus a duplicate of #676.

**Closed by PrimaryFeather** 2015-03-25 16:32 UTC

**Comment by Mintonist** [comment] 2015-03-25 17:52
PrimaryFeather, Thx for answer.

Please tell me, if we change a few of the limits in AGALMiniAssembler, how it influences on old devices (which supports only baseline/baselineConstrained profile)?
Seems we need to have versions of AGALMiniAssembler for every profile? Am I wrong?

**Comment by PrimaryFeather** [comment] 2015-03-26 07:19
You're welcome!

No, we don't need separate versions of AGALMiniAssembler for each profile; that class is backwards compatible. And if you use Starling, none of the limits will be reached, since all Starling code is compatible with "baselineConstrained" profile. 

So if you use Starling as it is, with its included AGALMiniAssembler, there won't be any problems. The problem you've got is related to something different: a problem with the Stage3D implementation on Android.

**Comment by Mintonist** [comment] 2015-03-26 08:10
> all Starling code is compatible with "baselineConstrained" profile.
Does it mean that we have no perfomance boost with AIR17 on newest smartphone which support 'standart/standartExtended' profile?

**Comment by PrimaryFeather** [comment] 2015-03-26 13:07
Yes, it means that the performance does not change with the newest profile. The new profile allows developers to write more complex pixel and vertex shader code (AGAL), and that can potentially lead to faster games. But with the default Starling code, nothing will change.

In fact, at the moment, I'd recommend to prefer the following profiles:

```as3
["baselineExtended", "baseline", "baselineConstrained"]
```

Pass them like this as the last argument to the Starling constructor.

That's because "baseline" allows more efficient texture usage, and "baselineExtended" supports 4k textures. Profiles above that don't make any difference in Starling.
