### ISSUE TITLE
Android textures getting cropped - workaround?

### ISSUE THREAD

**Issue by tconkling** [Gamua/Starling-Framework#1012] opened 2017-12-13 01:03 UTC
### Preamble!

I'm being bitten by a very old AIR-on-Android issue, described in detail on the Starling forum: https://forum.starling-framework.org/topic/textures-partially-uploaded-to-gpu-original-bitmapdata-is-perfect

In short, on Android, textures will occasionally be "cropped" when uploaded to the GPU: all texels below a certain line in the texture will render as invisible. There's no programmer-observable rhyme or reason to when this occurs, and quitting and restarting the game will frequently solve the problem. Here's an example from my game. I've circled the areas subtextures are cropped or completely invisible:

![broken](https://user-images.githubusercontent.com/709022/33915964-44da0a76-df5b-11e7-95f4-bc73a85a2081.jpg)

Here's what the screen should look like:

![working](https://user-images.githubusercontent.com/709022/33915985-5e8f8b6c-df5b-11e7-8401-9fe54065378c.png)

Folks have been reporting this issue way back since AIR 19, and it's still recurring as of AIR 27. Adobe's been notified of it several times. The original Adobe tracker bug was seemingly lost when Adobe updated their bug tracking; a new bug is here: https://tracker.adobe.com/#/view/AIR-4198475

### Actually getting to the point!

Adobe seems to have like 1/2 an engineer on AIR these days, so the chances of them fixing this bug are slim. My game is blocked until this is fixed or I can work around it. 

Anecdotally, it sounds like there's a potential workaround: after creating a ConcreteTexture on Android, immediately draw that texture to a render-texture and compare the results with the source image that was uploaded to the GPU. If there's a mismatch, recreate the texture.

I'd love for this workaround to be baked into Starling itself (presumably via an opt-in flag that client code can set on Starling during initialization, e.g. `Starling.validateTextureAfterUpload` or something). This would obviously slow texture loading (hence the opt-in), but better a slightly slower load than a broken game.

@PrimaryFeather, does this sound reasonable? I'm happy to take a stab at this and make a PR if it seems like something you'd want in Starling. It looks like `ConcretePotTexture.uploadBitmapData` and `ConcreteRectangleTexture.uploadBitmapData` could check a Starling flag and perform this validation in a loop (with some low number of maximum iterations), delaying any `TextureReady` event until successful?

**Comment by PrimaryFeather** [comment] 2017-12-13 12:25
Damn, so this one has bitten you, too. Sorry to hear about those troubles! 😣 

You're right, a workaround would be a huge help, and I'd be willing (while holding my nose) to add something like that to Starling — however, how do you plan to check what's inside the texture? There is no way to read pixels from the texture, after all. Well, we could draw it to the back buffer and use "context.drawToBitmapData", but that might lead to flickering on the back buffer — at least I sometimes noticed this in the past. Maybe it's worth a shot; I don't see an easier way.

Nevertheless, I'd like to make another attempt to get this to Adobe, in parallel with you making the pull request. I've got a few questions for you to get this started.

* It seems to me that you can reproduce the problem quite reliably, is that right? 
* What you said about re-installing / rebooting — is that *always* what happens on affected devices?
* How many Android devices do you have for testing, and on how many (and which) does the issue pop up?
* Did you try to check the pixel values in the BitmapData directly prior to uploading — I guess that's still containing the correct values?
* Would you be willing to share the game (maybe stripped down) with Adobe, possibly with source? 

Thanks a lot in advance, Tim!

**Comment by tconkling** [comment] 2017-12-13 18:30
Yeah, my plan is to do something along these lines (using the technique described by FatRedBird, in this thread: https://github.com/Gamua/Adobe-Runtime-Support/issues/25)

```
        var maskColor:uint = 0xFF000000;
        var emptyColor:uint = 0x00000000;

        var tex :Texture = Texture.fromBitmapData(sourceBitmap, false, false, _scale);

        if (_validateAfterCreation) {
            var bounds1:Rectangle = sourceBitmap.getColorBoundsRect(maskColor, emptyColor, false);
            var renderBitmap :BitmapData = new BitmapData(sourceBitmap.width, sourceBitmap.height, true);
            var valid :Boolean;
            for (var ii :int = 0; ii < 3 && !valid; ++ii) {
                var image :Image = new Image(tex);
                image.drawToBitmapData(renderBitmap);
                var bounds2:Rectangle = renderBitmap.getColorBoundsRect(maskColor, emptyColor, false);
                valid = bounds1.equals(bounds2);
                if (!valid) {
                    tex = Texture.fromBitmapData(sourceBitmap, false, false, _scale);
                }
            }
        }

        if (!valid) { throw an error or log a warning; }
```

- I can reproduce the the issue with *some* reliability. The QA team that evaluates the game currently pegs the reproducibility at 2/30. Most of my Android testing is on an Nvidia Shield tablet, and my experience is that it occurs for me in about 3/10 launches, with the frequency going up a bit after a device reboot.
- Re-installing/rebooting: no, this does not always trigger the bug. Anecdotally, it _seems_ to be recur more dramatically/frequently after a device reboot, but the turnaround time for that particular test is pretty long so I don't have good data on it currently. (But I'll continue gathering data.)
- This is happening to me on my Nvidia Shield. The QA team has reproduced it on a Samsung Note 4 and an Nvidia Shield. I'll reach out to the QA team to see if there are other devices on which this does *not* occur - I'm not sure the entire range of devices they're using.
- I haven't checked the BitmapData before uploading, but I'll do that today.
- I'd be willing to share my code with Adobe, yeah. My game is ~100k LOC, though, and it'll be a bit of a pain to get the complex-ish build process into a place where they can build the game without handholding from me. That said, if the existing test case that's attached to the Adobe Tracker bug isn't enough for their purposes, I would do what I can - this game is launching very soon for iOS, and I'm worried that I simply won't be able to launch simultaneously on Android. (Also, I live in San Francisco - I'm not sure if the AIR team works out of the Adobe office here, but if so, I'd be happy to visit them and walk them through the bug.)

**Comment by tconkling** [comment] 2017-12-14 00:42
An update, after a day spent working on this:

I ended up using this (really crappy) code for texture validation:

```
public static function createFromBitmap (sourceBitmap :BitmapData, scale :Number, validate :Boolean, name :String = null) :Texture {
    if (!validate) {
        return Texture.fromBitmapData(sourceBitmap, false, false, scale);
    }

    const MASK_COLOR :uint = 0xFF000000;
    const EMPTY_COLOR :uint = 0x00000000;

//        var srcBounds :Rectangle = sourceBitmap.getColorBoundsRect(MASK_COLOR, EMPTY_COLOR, false);
    var renderBitmap :BitmapData = new BitmapData(sourceBitmap.width, sourceBitmap.height, true);
    var tex :Texture = null;
    var valid :Boolean = false;
    for (var ii :int = 0; ii < 3 && !valid; ++ii) {
        if (tex != null) {
            tex.dispose();
        }
        tex = Texture.fromBitmapData(sourceBitmap, false, false, scale);
        var image :Image = new Image(tex);
        image.drawToBitmapData(renderBitmap, EMPTY_COLOR, 0.0);

//            var renderBounds :Rectangle = renderBitmap.getColorBoundsRect(MASK_COLOR, EMPTY_COLOR, false);
//            valid = renderBounds.equals(srcBounds);
        valid = compareBitmaps(sourceBitmap, renderBitmap);
        if (!valid) {
            log.warning("Texture doesn't match source bitmap", "name", name, "tries", ii + 1);
        }
    }

    renderBitmap.dispose();

    return tex;
}

private static function compareBitmaps (src :BitmapData, dst :BitmapData) :Boolean {
    if (src.width != dst.width || src.height != dst.height) {
        return false;
    }

    for (var yy :uint = 0; yy < src.height; ++yy) {
        for (var xx :uint = 0; xx < src.width; ++xx) {
            var srcPx :uint = src.getPixel32(xx, yy);
            var dstPx :uint = src.getPixel32(xx, yy);
            if (Color.getAlpha(srcPx) != 0 && srcPx != dstPx) {
                return false;
            }
        }
    }

    return true;
}
```

(I'm comparing the two bitmaps pixel by pixel, rather than using the `BitmapData.getColorBoundsRect` technique, because I cannot get `getColorBoundsRect` to behave as expected. I'm using it to find the bounds of the non-transparent pixels in both bitmaps, but I'm getting unequal bounds results with this code even on platforms that load textures properly. So either `getColorBoundsRect` is broken or my understanding of it is.)

BUT: with this code in place, I _never_ trigger the "Texture doesn't match source bitmap" warning. A true heisenbug. Does the `drawToBitmapData` possibly prevent the error from occurring? Is there a race condition in AIR texture creation/upload on Android? Did I just get unlucky in the dozen or so times I ran the code with this "fix" in place? Who knows.

**Comment by PrimaryFeather** [comment] 2017-12-14 08:07
Thanks a lot for all the additional information, Tim, and for trying out that workaround code!

>  That said, if the existing test case that's attached to the Adobe Tracker bug isn't enough for their purposes [...]

Which test case do you mean? Unfortunately, there is no test case attached — despite me constantly talking about it, no one ever posted an actual sample project that's confirmed to reproduce the issue. If you'd be able to do that, you'd be my personal (Anti?) hero! :wink:

I must admit I only just read about that `getColorBoundsRect` method — somehow, I never noticed it before. So I can't say if you're using it the right way (although from the documentation, I would also have expected the code you wrote to work).

However, if this continues to *not* pop up while that code is included, this might be a great pointer as to the internal reason for the bug. I agree: this sounds like a race condition triggered by the texture creation code. Something inside `image.drawToBitmapData` must prevent it from happening.

**Comment by tconkling** [comment] 2017-12-14 18:24
You're right. I could've sworn there was sample code that reproduced the bug on affected devices; maybe in the original bug that was lost during the bugbase switchover? Regardless, I'll work on creating a test case today.

**Comment by tconkling** [comment] 2017-12-14 21:48
I've created a small project that reliably reproduces the bug on my tablet. It's here: https://github.com/tconkling/AIRAndroidCroppedTextures. There's a video of my repro'ing the bug here: https://www.youtube.com/watch?v=v0M1Z00_rUU&t=27s. (This is also linked in the Github project.)

**Comment by PrimaryFeather** [comment] 2017-12-15 08:06
Thanks a lot for the big efforts on getting this reproduced with sample code and video! That will be a HUGE help to get this looked into and hopefully fixed. I'll post the links to those resources to all relevant reports and will give Adobe another heads-up. Depending on the feedback I'm getting, I'll also decide on including that workaround code in Starling.

I'll keep you updated, Tim!

**Comment by tconkling** [comment] 2017-12-15 18:30
Great, thanks Daniel

**Comment by tconkling** [comment] 2017-12-19 00:18
@PrimaryFeather - Adobe's updated the bug to say that they can repro it and are working on a fix.

In the meantime - as my game is due to ship in the early new year and Adobe AIR releases are months apart - I need to make do with AIR 28 (which doesn't fix the bug). It turns out my workaround, above, was broken in a boneheaded way: in `compareBitmaps`, I'm assigning `dstPx` from the source bitmap, so the comparison doesn't do anything.

I've fixed that, but I'm having a couple issues with `DisplayObject.drawToBitmapData`: (You may  like a separate bug for these issues, which I'm happy to create - let me know)

- Texture scaling and stage contentScaleFactor seem to be improperly handled. If textureScale and contentScaleFactor match up, things look fine; otherwise the resultant texture seems to be scaled by contentScaleFactor/textureScale. It looks like this is fixed by multiplying the source `DisplayObject`'s scale by the inverse of this, e.g.:

```
var textureImage :Image = new Image(texture);
textureImage.scale = texture.scale / Starling.current.contentScaleFactor;
var bitmap :BitmapData = textureImage.drawToBitmapData();
```

- The resulting texture will be cropped if it's bigger than the context 3D back buffer. (My textures are mostly 2k-by-2k atlases, so they're always cropped.) This seems to be a limitation of Flash and there probably isn't a way around it other than by drawing in multiple passes, with each pass handling a different chunk of the texture? But possibly worth noting in the docs.

(I think this second issue can be overcome for the purposes of working around this texture bug, as we only need to compare the bottom-most row of non-transparent pixels in the source bitmap to the same row in the rendered bitmap - bugged textures are always vertically cropped at an arbitrary offset from their bottom.)

**Comment by PrimaryFeather** [comment] 2017-12-19 10:46
> @PrimaryFeather - Adobe's updated the bug to say that they can repro it and are working on a fix.

Hurray, that's great news! Let's hope they get to the root of this issue.

> Texture scaling and stage contentScaleFactor seem to be improperly handled.

Could you send me a complete example of the problem you're seeing? I can't quite get to reproduce it. Beware, though, that the "BitmapData" itself does not have any scale factor, so you need to take the different coordinate system into account when accessing it — or assign the correct scale factor when you convert it back to a texture.

> The resulting texture will be cropped if it's bigger than the context 3D back buffer.

Yes, that's currently a limitation. Since stage3D only supports reading back pixels from the back buffer (not, say, a render texture), the `drawToBitmapData` method draws to the back buffer as it's currently configured for the application. I'll have to try if it's possible to temporarily resize it beyond the bounds of the current application. 

In any case, as long as there is no proper workaround, I will add this information to the docs. Thanks for the reminder!!

**Comment by tconkling** [comment] 2017-12-20 18:42
@PrimaryFeather, re: complete example -- do you mean a working application, or simply a screenshot of what I'm seeing alongside a code snippet?

Also, it turns out - for my test devices at least - that it's the bitmap loading that is failing, and not texture creation. I wrote more about it here, https://github.com/Gamua/Adobe-Runtime-Support/issues/25. So my findings are significantly different from @FatRedBird's (whose results I couldn't replicate), and I wonder if he was simply mistaken or if there are in fact multiple bugs here?

**Comment by PrimaryFeather** [comment] 2017-12-21 10:36
> do you mean a working application, or simply a screenshot of what I'm seeing alongside a code snippet?

Screenshot (or explanation text) + code snippet would be totally sufficient! 

> Also, it turns out - for my test devices at least - that it's the bitmap loading that is failing, and not texture creation.

Oh wow, so it _is_ the bitmap loading that's the problem. Some users in the old forum thread suspected something like that, but we never managed to proof this via an example. You're right, this *could* mean that we're looking at two different things here. On the other hand, the phenomenon is so similar ... hm.

**Comment by PrimaryFeather** [comment] 2017-12-21 10:41
BTW, I'm happy to hear you found a workaround that sounds feasible for the time being! Hopefully it finally gets fixed at its root — thanks to you, it's now possible — but it's good that this isn't a show stopper any longer.

**Comment by tconkling** [comment] 2017-12-22 01:21
Sure - here's a function that takes a texture, draws it onscreen in an untransformed `Image`, and then renders that Image to a bitmap with the same dimensions as the texture, creates a new texture from the bitmap, and draws that to the screen next to the original image:

```actionscript
private function drawTexture (tex :Texture) :void {
    // draw the texture
    var texImage :Image = new Image(tex);

    // render the texture to a bitmap, turn that into a new texture, and draw that
    var renderBitmap :BitmapData = new BitmapData(tex.nativeWidth, tex.nativeHeight, true);
    texImage.drawToBitmapData(renderBitmap);
    var renderTex :Texture = Texture.fromBitmapData(renderBitmap, false, false, tex.scale);
    var bitmapImage :Image = new Image(renderTex);

    // show the two images onscreen (snip)
}
```

Here are the results with a sample texture from my game. My textures all have a scale of 2, and at the game's default resolution, 1024x768, `Starling.contentScaleFactor` is also 2 -- the texture scale and contentScaleFactor are equal. Here's what that looks like (original texture on the left, rendered texture on the right):

![screen shot 2017-12-21 at 5 09 45 pm](https://user-images.githubusercontent.com/709022/34281286-7baed4e6-e672-11e7-8e64-64cbd38d09a2.png)

When I fullscreen my game on my monitor, `Starling.contentScaleFactor` gets set to 4. Here's the results of running the same function when contentScaleFactor is larger (this screenshot and its contents are larger than the previous, but this is simply because the game is scaled up to account for the big jump in resolution):

![screen shot 2017-12-21 at 5 09 56 pm](https://user-images.githubusercontent.com/709022/34281307-b6e33fb6-e672-11e7-9f28-87dfcc1f55d1.png)

(If the source texture has a larger scale than `Starling.contentScaleFactor` -- if I were to run the game at a super tiny resolution -- that texture will be shrunken in the resulting bitmap.)

Client code can fix this by scaling the source Image before calling `drawToBitmapData`, like so:
```
texImage.scale = (tex.scale / Starling.current.contentScaleFactor);
texImage.drawToBitmapData(renderBitmap);
```

**Comment by PrimaryFeather** [comment] 2017-12-22 08:12
Mhm, as you already guessed, this is actually working as intended, but I can see why this is a little confusing. 

I think the problem is this: you're treating `drawToBitmapData` as if it was a method on _Image_, not _DisplayObject_. If it were on _Image_, I could take the image texture's `scale` factor into account and create the bitmap data in its optimal size. However, as it's a method on _DisplayObject_, I don't know anything about a texture. The object could be a _Canvas_ or an untextured _Quad_, or a _Sprite_ with all different kinds of objects.

Thus, Starling will do the second best thing and use the "dpi" of the stage, if you will. The result is _BitmapData_ that, if converted to a texture, should use Starling's current `contentScaleFactor`. Your code would look like this:

```as3
// draw the texture
var texImage :Image = new Image(tex);

// render the texture to a bitmap, turn that into a new texture, and draw that
var renderBitmap :BitmapData = texImage.drawToBitmapData();
var renderTex :Texture = Texture.fromBitmapData(renderBitmap, false, false, Starling.contentScaleFactor);
var bitmapImage :Image = new Image(renderTex);
```

That way, the two images will have the same size & resolution.

Again, you already expected that — I just wanted to describe my reasoning in a little more detail so it's comprehensible. In a nutshell, `drawToBitmapData` is a generic method that must work the same for all display objects, and that's why it behaves as it does. :smile:

**Comment by ll24llll** [comment] 2018-04-09 09:04
Hello,
I have the same problem, some Textures are partially previewed, cropped or completely invisible.
I'm using AssetManager class to get textures from atlas files. So the workaround introduced above doesn't work for me. I don't have access to BitmapData of SubTextures of atlas files.

Is this problem going to get fixed?

**Comment by PrimaryFeather** [comment] 2018-04-10 08:54
I recently rewrote the whole _AssetManager_ architecture, so it would be possible to implement [Tim's solution](https://github.com/Gamua/Adobe-Runtime-Support/issues/25#issuecomment-353145724) via an extension to that.

However, the problem remains that the final row often *is* empty/transparent, so I'm not sure yet how best to automate detection. I'll try to think of something! @ll24llll, how reliably can you reproduce the problem? If I sent you some test-code, would you be able to verify if it works?

**Comment by ll24llll** [comment] 2018-04-12 06:14
Dear Daniel,
I'll check out the new AssetManager as soon as possible, thanks.

Unfortunately I can not reproduce the problem myself, but some of my clients are sending me screen captures like this every now and then: [picture link](http://s9.picofile.com/file/8323517618/tank_texture_bug.jpg)

By implementing Tim's solution and tracking it, I'll be aware of that how much and in which situations the problem is occurring.

**Comment by tconkling** [comment] 2018-04-14 22:30
AIR 29 claims to have fixed this issue - have you tried the latest version?

**Comment by ll24llll** [comment] 2018-04-15 05:33
Dear Tim,
I implemented AIR29 the day before yesterday and I've not published an
update thereafter. I'll let you know if the problem persists.

**Comment by PrimaryFeather** [comment] 2019-03-08 09:23
I haven't seen this problem reported since that mentioned AIR update, so I'm supposing this is fixed! I'll close the issue now, but if anyone reports differently, we can open it up again anytime.

**Closed by PrimaryFeather** 2019-03-08 09:23 UTC
Labels: Bug in Flash/AIR, Feature
