### ISSUE TITLE
Bug with BitmapFont

### ISSUE THREAD

**Issue by subdan** [Gamua/Starling-Framework#885] opened 2016-07-21 15:20 UTC
I want to modify the BitmapFont class to dynamically generate some characters. I want to display a fraction instead of special symbols. For example: I want to display this text:
Some Ӑ text
as:
![screenshot_2](https://cloud.githubusercontent.com/assets/410293/17028212/7ddcb558-4f6f-11e6-8a7c-f85bb8bbb922.png)

Inside parseFontXml method I found a loop:
```
 for each (var charElement:XML in fontXml.chars.char)
            {
                var id:int = parseInt(charElement.@id);
                var xOffset:Number  = parseFloat(charElement.@xoffset)  / scale;
                var yOffset:Number  = parseFloat(charElement.@yoffset)  / scale;
                var xAdvance:Number = parseFloat(charElement.@xadvance) / scale;
                
                var region:Rectangle = new Rectangle();
                region.x = parseFloat(charElement.@x) / scale + frameX;
                region.y = parseFloat(charElement.@y) / scale + frameY;
                region.width  = parseFloat(charElement.@width)  / scale;
                region.height = parseFloat(charElement.@height) / scale;
                
                var texture:Texture = Texture.fromTexture(mTexture, region);
                var bitmapChar:BitmapChar = new BitmapChar(id, texture, xOffset, yOffset, xAdvance); 
                addChar(id, bitmapChar);
            }
```
I added a condition:
```
                if (id == 1232) // I want to replace the symbol Ӑ with dynamic texture
                {
                    texture = Texture.empty(100,100); // I create a new empty texture (for testing)
                }
```
I see the next picture:
![screenshot_1](https://cloud.githubusercontent.com/assets/410293/17027937/94ddcfe0-4f6e-11e6-8c12-2befcae7c4f1.png)

It's a TextField:
`var tf:TextField = new TextField(400, 100, "Some Ӑ text");`
I replace Ӑ symbol with empty Texture.

Why I see a font texture atlas instead of empty space?
![screenshot_3](https://cloud.githubusercontent.com/assets/410293/17028385/1b6f8d36-4f70-11e6-9e32-6a3e3861bb02.png)

In the future I will replace Texture.fromEmpty to RenderTexture. Inside RenderTexture I will combine 3 Image: numerator, denominator and separator.

This bug appears in all versions of Starling.

**Comment by PrimaryFeather** [comment] 2016-07-22 06:54
The reason for this issue is that the text is drawn into a `MeshBatch`, on order to provide the maximum performance. And all quads that are added to a MeshBatch need to reference the same texture. The empty texture you're adding is just ignored; the batch can't work with that. Instead, it references the font texture, and that's what you're seeing.

My recommendation for what you want to achieve: use `BitmapFont.createSprite` instead. You'll get a sprite where each glyph is one image. Use placeholders for the positions where you want to show the fractions; then replace those placeholders with the manually created fraction symbols.

However what's happening inside `fillMeshBatch` is intentional — so this is not a bug. I'll close this issue.

**Closed by PrimaryFeather** 2016-07-22 06:54 UTC

**Comment by subdan** [comment] 2016-07-22 07:04
Thank you, Daniel.
