### ISSUE TITLE
set displayState and setAspectRatio

### ISSUE THREAD

**Issue by denisgl777** [Gamua/Starling-Framework#1000] opened 2017-08-30 18:02 UTC
If the display changes state, the context is lost (iOS, AIR 25)
I think it's not a secret.
In this regard, contacted the adobe?

if Starling.current.nativeStage.setAspectRatio( StageAspectRatio.ANY);
change to
Starling.current.nativeStage.setAspectRatio( StageAspectRatio.PORTRAIT);

The display  in normal mode goes to full screen
And, consequently, the loss of context

**Comment by PrimaryFeather** [comment] 2017-08-31 12:43
Could you please open up an issue on [Adobe Tracker](https://tracker.adobe.com/) and [Adobe Runtime Support](https://github.com/Gamua/Adobe-Runtime-Support)?

Don't worry, you can post the very same report in both issue trackers. Find a detailed explanation [in this post I made in the Starling Forum](https://forum.starling-framework.org/topic/important-new-issue-tracker-for-adobe-air).

In any case, creating the issue over there, with an easy-to-reproduce sample, would raise our chances of getting Adobe fixing this. Thanks a lot in advance!

**Comment by PrimaryFeather** [comment] 2017-08-31 12:43
Since there's nothing I can do in Starling to work against this bug, I'll close this issue here.

**Closed by PrimaryFeather** 2017-08-31 12:43 UTC
Labels: Bug in Flash/AIR
