### ISSUE TITLE
[Request] Make it possible to use RenderTexture with third party code

### ISSUE THREAD

**Issue by b005t3r** [Gamua/Starling-Framework#714] opened 2015-05-13 09:00 UTC
What I'm trying to do:

```as3
var tex:RenderTexture = new RenderTexture(...); // creates a RenderTexture, which uses two textures internally
tex.draw(imageA);
tex.draw(imageB);

var myRenderer:MyRenderer = new MyRenderer();
myRenderer.renderToTexture(tex); // renders to RenderTexture

tex.draw(imageC); 
```

The problem is, if ```imageC``` is rendered, the texture is cleared and content created by ```myRenderer.renderToTexture(tex)``` call is not preserved.

It would be great if there were a method I could call before/after using ```myRenderer``` to preserve the output it creates.

**Comment by PrimaryFeather** [comment] 2015-05-13 09:04
Actually, I don't understand why the texture is cleared when imageC is rendered. Could it be that there's a "context.clear" call executed by "myRenderer"?

Furthermore, have you created the RenderTexture with the "persistent" parameter set to "true"?

**Comment by b005t3r** [comment] 2015-05-13 09:07
Hmm, now when you asked, maybe that's something on my side...

I create RenderTexture with ```persistent``` set to ```true``` and I though this is what's causing the problems. But if you say it's not it, I guess it's something on my side probably.

**Comment by PrimaryFeather** [comment] 2015-05-13 09:11
As a first step, make the draw calls like this:

```as3
tex.drawBundled(function():void
{
    tex.draw(imageA);
    tex.draw(imageB);
    // ...
});
```

That's more efficient and should even cause less problems.

**Comment by b005t3r** [comment] 2015-05-13 09:36
After going through the code, I think it's the RenderTexture that's responsible, but I have no idea why :)

I tested with ```myRenderer``` rendering to a "fresh" texture (nothing has been rendered onto it yet), it does set it as a render target (by calling ```context.setRenderToTexture(outputTexture.base)``` and it does clear it (it calls ```context.clear(...)```) and that's it. Then I call something like ```tex.draw(imageC);``` and the contents rendered by ```myRenderer``` are gone. If I comment out the ```tex.draw(imageC);``` the contents are still there.

**Comment by b005t3r** [comment] 2015-05-13 09:51
OK, the problem was RenderTexture's member ```mBufferReady``` was not set, so I needed to ```clear()``` the texture after creating one to set ```mBufferReady``` to ```true```.

**Comment by PrimaryFeather** [comment] 2015-05-13 12:24
Ah, I see! And does "drawBundled" change anything?

**Comment by b005t3r** [comment] 2015-05-13 13:01
It won't change anything, ```myRenderer``` does not use RenderTexture's ```draw()``` or ```drawBundled()```, it uses custom shaders and Context3D ```drawTriangles()```.

But with my current project, the problem is gone, if I call RenderTexture's ```clear()``` before doing any custom rendering on it.

**Comment by PrimaryFeather** [comment] 2015-05-13 13:09
Ah, okay.
Then it seems the problem is solved, right? Which means I'll close the issue. =)

**Closed by PrimaryFeather** 2015-05-13 13:09 UTC

**Comment by b005t3r** [comment] 2015-05-13 13:29
Yeah, it's kind of solved. I can think of different scenarios which won't work probably (I still think the original example I gave won't work, because I'd need to clear the texture anyway, so at least the second draw() call's results would be erased), but everything works with my current approach :)
