### ISSUE TITLE
Sprite3D and hitTest

### ISSUE THREAD

**Issue by fred1024** [Gamua/Starling-Framework#775] opened 2015-10-19 09:59 UTC
Hello, I am having some troubles with the Sprite3D hitTest function ... been going through starling and came around this ... so I was wondering ..
the hitTest function of Sprite3D is expecting local coordinates but in this function those "local coordinates" get transformed by the inverse of the local transform of the sprite3D. So making those coordinates relative to the parent of the sprite3D

in Sprite3D hitTest

```as3
sHelperMatrix.copyFrom(transformationMatrix3D);
sHelperMatrix.invert();

stage.getCameraPosition(this, sHelperPoint);
MatrixUtil.transformCoords3D(sHelperMatrix, localPoint.x, localPoint.y, 0, sHelperPointAlt);
```

is that all right ?
Actually if i give global coordinate for the touch it works fine if i give local coordinates it doesn't ... does anyone add the same issue ? .. i think I must be doing something wrong as i think i should have found other threads about that.

**Comment by PrimaryFeather** [comment] 2015-10-20 17:56
This method is not easy to understand ... I had to think about this myself for a while when I looked into it again. The matrix stuff, especially in 3D, always makes my head start spinning. ;-)

It's easiest to understand when you compare it to the standard 2D hitTest method of the `DisplayObjectContainer` class:

```as3
for (var i:int = numChildren - 1; i >= 0; --i) // front to back!
{
    var child:DisplayObject = mChildren[i];

    sHelperMatrix.copyFrom(child.transformationMatrix);
    sHelperMatrix.invert();

    MatrixUtil.transformCoords(sHelperMatrix, localX, localY, sHelperPoint);
    target = child.hitTest(sHelperPoint, forTouch);

    if (target) return forTouch && mTouchGroup ? this : target;
}
```

The part in the middle is very similar: we take the inverted transformation matrix of the child to find out where "localX" and "localY" will be in the child's coordinate system. That's what we pass to the child's hit test.

Now, the 3D variant starts just the same; it just uses the 3D transformation matrix — this time, from "this", not from the child. 

Why? Let's say the parent of the Sprite3D is a DisplayObjectContainer (it normally is). According to the code I pasted above, it will use the 2D transformation matrix to get "localX/Y" into the Sprite3D's coordinate system. But that won't have worked, because the 2D transformation matrix of a Sprite3D is always the identity matrix! So the points are not yet in the correct coordinate system. We're doing this now, with the 3D transformation matrix. After that transformation, we have the coordinates in the local coordinate system of the Sprite3D.

Then we find out the camera position in the local coordinate system as well, and that's all we need. With this information, we can intersect the 3D line between the camera and the hit point, and find out where it ends up in the 2D coordinate system that the Sprite3D's children are living in. Via the "super" call, that coordinates will then be transformed into the coordinate systems of all children.

Phew! Quite a bit going on in these few lines. I hope that information helped!
As far as I know, this is working just fine — at least it does in my tests, and I haven't heard any other complaints yet.

**Comment by fred1024** [comment] 2015-10-23 15:06
Thanks a lot for your answer .... I think I get it but then maybe i have found a test case you should have a look at. let say I have something like this with the touch event listener on _sprCard

/// INIT //
			_sprCont = new Sprite3D();
			addChild(_sprCont);
			_sprCard = new Sprite3D();
			_sprCard.addEventListener(TouchEvent.TOUCH, onTouch);
			_sprCont.addChild(_sprCard);
			_sprCardBack = new Image(assets.getTextureAtlas("shader-fx-no-pma").getTexture("clouds_test") as SubTexture);
			_sprCard.addChild(_sprCardBack);

// TOUCH
		private function onTouch(e : TouchEvent) : void {
			var touch : Touch = e.getTouch(_sprCard);
			if (touch) {
				switch (touch.phase) {
					case TouchPhase.BEGAN:
						break;
					case TouchPhase.HOVER:
						break;
					case TouchPhase.ENDED:
						// Allow cancelling by moving the touch out of the target
						var location : Point = touch.getLocation(_sprCard);
						if (hitTest(location, true)) {
							trace("selected");
						}
						break;
				}
			}
		}

That wouldn't work if _sprCard is not at 0,0 ... (offseted)
I have looked at touch.getLocation(_sprCard) to get local coordinates for the hitTest and the matrix3D is applied to the returned coordinates ... then are transformed a second time in the hitTest with the same matrix3D.
That must be related to the hierarchy I am using and where I have put the listener but I must stick to this structure.

Thanks a lot for your support
Starling is really nice and powerful, I am playing a lot with fragment filters :)  can't wait for Starling2 :)

**Comment by PrimaryFeather** [comment] 2015-10-27 14:50
I'm afraid I can't follow your sample 100% :wink:
Do you think you could create a complete, minimal sample I can compile and try out? That would help a lot. Thanks in advance!

And thanks for the nice words about Starling! I'm looking forward to finally making my 2.0 branch public — hopefully, I'll be able to do that soon!

**Comment by PrimaryFeather** [comment] 2016-04-14 09:28
Lacking that minimal sample, I'll close this issue for now. Feel free to open it again if you found an example that I can use to reproduce this.

**Closed by PrimaryFeather** 2016-04-14 09:28 UTC
Labels: Discussion
