### ISSUE TITLE
memory leak problem with blurfilter

### ISSUE THREAD

**Issue by KarenArushi** [Gamua/Starling-Framework#758] opened 2015-08-27 00:51 UTC
My English is very poor. please understand.
I just download the latest sources from here which is 1.7.1(Starling.VERSION)

When I try code like this

```ActionScript3
var image:Image = new Image("texture")
var mfilter:BlurFilter = new BlurFilter(5, 5, 5);
image.filter = mfilter;
addChild(image);

//more filter, more leak
/*var image2:Image = new Image("texture")
var mfilter2:BlurFilter = new BlurFilter();
image2.filter = mfilter2;
addChild(image2);*/
```

and open Windows Task Manager. It shows flash player process memory keep rise.
I have tried to dispose mfilter and memory not rise anymore, but is not drop either. Then I tried `removeChild(image, true)`, same situation, no rise and no drop. And I have tried new BlurFilter with out parameters, still not work. My tester play my game about 40minute and it cost 1.6GB memorys.

In fact Starling Demo has same problem too, even identity filter. Is much slower than my (I used about 5 blurfilter on 5 different image and movieclips) but is still a leak.

I asked some body and they seems dont have this problem. so I did some test my self.
First I tried demo on website, is works well, no leak. Then I put my game in to browser, works well too.
And I tried demo_mobile, works well. But my game was not good no mobile. (I think this is my problem because that is a very old version of my game).

So, seems this situation only happend when I use standalone flash player, both on version 17 and 18.
I know Im not gonna release my game with standalone flash player. But I think is best to let you know : )

**Comment by PrimaryFeather** [comment] 2015-08-27 08:16
Thanks a lot for the report!

I just tried it out with the Starling demo, and indeed, I can reproduce it — at least in Windows. On OS X, the memory stays constant.

Since the SWF is always the same, this must be a problem in the standalone player. I'll try again with Scout to see if it shows more information about the leaking memory.

**Comment by PrimaryFeather** [comment] 2015-08-27 12:17
Scout shows constant memory usage — which is another indicator that it's a problem in the Flash Player, not in the Starling code.

I reported the issue in Adobe's bug base:
https://bugbase.adobe.com/index.cfm?event=selectBug&CFGRIDKEY=4044551

Please vote for the bug, so that it gets to Adobe's attention.

Again, thanks a lot for the report! I'll close the issue here, since it's probably not a Starling issue. We can reopen the issue if it turns out otherwise.

**Closed by PrimaryFeather** 2015-08-27 12:17 UTC
Labels: Bug in Flash/AIR
